export const CUSTOMER_COLLECTION = "customers"
export const WORKERS_COLLECTION = "workers"
export const LOCATION_COLLECTION = "location"
export const WORKERS_SERVICES_COLLECTION = "services"
export const VERIFY_CUSTOMER_URL ="http://localhost:5000/customer/verify-email/"
export const VERIFY_WORKER_URL ="http://localhost:5000/customer/verify-email/"